Repository GeorgeWeb/dwarfworks, pull requests merged in 2019-10, with the labels that each got.

#16 Add Layers
  Dwarfworks/Source/Dwarfworks/Core/Application/Application.cpp
  Dwarfworks/Source/Dwarfworks/Core/Application/Application.h
  Dwarfworks/Source/Dwarfworks/Core/Core.h
  Dwarfworks/Source/Dwarfworks/Core/EntryPoint.h
  Dwarfworks/Source/Dwarfworks/Core/Layers/Layer.cpp
  Dwarfworks/Source/Dwarfworks/Core/Layers/Layer.h
  Dwarfworks/Source/Dwarfworks/Core/Layers/LayerStack.cpp
  Dwarfworks/Source/Dwarfworks/Core/Layers/LayerStack.h
  Sandbox/Source/Sandbox.cpp
  premake5.lua
Labels: enhancement

#34 Add Input Polling and Events
  Dwarfworks/Source/Dwarfworks.h
  Dwarfworks/Source/Dwarfworks/Core/Application/Application.cpp
  Dwarfworks/Source/Dwarfworks/Core/Application/Application.h
  Dwarfworks/Source/Dwarfworks/Core/Input/Input.h
  Dwarfworks/Source/Dwarfworks/Core/Input/KeyCodes.h
  Dwarfworks/Source/Dwarfworks/Core/Input/MouseButtonCodes.h
  Dwarfworks/Source/Dwarfworks/Platform/Windows/WindowsInput.cpp
  Dwarfworks/Source/Dwarfworks/Platform/Windows/WindowsInput.h
  Dwarfworks/Source/Dwarfworks/Platform/Windows/WindowsWindow.h
  Sandbox/Source/Sandbox.cpp
Labels: enhancement :hammer:

#40 Add initial multi-threading support
  Dwarfworks/Source/Dwarfworks/Core/Application/Application.cpp
  Dwarfworks/Source/Dwarfworks/Core/Threading/TaskGenerator.cpp
  Dwarfworks/Source/Dwarfworks/Core/Threading/TaskGenerator.h
  Dwarfworks/Source/Dwarfworks/Core/Threading/TaskList.cpp
  Dwarfworks/Source/Dwarfworks/Core/Threading/TaskList.h
  Dwarfworks/Source/Dwarfworks/Core/Threading/ThreadManager.cpp
  Dwarfworks/Source/Dwarfworks/Core/Threading/ThreadManager.h
  Sandbox/Source/Sandbox.cpp
  premake5.lua
Labels: enhancement :hammer:

#49 Add graphics rendering context
  Dwarfworks/Source/Dwarfworks/Core/Layers/LayerStack.cpp
  Dwarfworks/Source/Dwarfworks/Core/Window/IWindow.h
  Dwarfworks/Source/Dwarfworks/Graphics/GraphicsContext.h
  Dwarfworks/Source/Dwarfworks/Platform/OpenGL/OpenGLContext.cpp
  Dwarfworks/Source/Dwarfworks/Platform/OpenGL/OpenGLContext.h
  Dwarfworks/Source/Dwarfworks/Platform/Windows/WindowsWindow.cpp
  Dwarfworks/Source/Dwarfworks/Platform/Windows/WindowsWindow.h
Labels: enhancement :hammer:

#50 Add OpenGL Triangle Test + OpenGL Info UI Test
  Dwarfworks/Source/Dwarfworks/Core/Application/Application.cpp
  Dwarfworks/Source/Dwarfworks/Core/Application/Application.h
  Dwarfworks/Source/Dwarfworks/Core/Core.h
  Dwarfworks/Source/Dwarfworks/Core/Layers/LayerStack.cpp
  Dwarfworks/Source/Tests/Test.cpp
  Dwarfworks/Source/Tests/Test.h
Labels: enhancement :hammer:

#51 Add Basic OpenGL Shader
  Dwarfworks/Source/Dwarfworks/Graphics/Shader.cpp
  Dwarfworks/Source/Dwarfworks/Graphics/Shader.h
  Dwarfworks/Source/Tests/Test.cpp
  Dwarfworks/Source/Tests/Test.h
Labels: enhancement :hammer:

#56 Add simple orthographic camera
  Dwarfworks/Source/Dwarfworks/Core/Application/Application.cpp
  Dwarfworks/Source/Dwarfworks/Core/Application/Application.h
  Dwarfworks/Source/Dwarfworks/Graphics/Camera.cpp
  Dwarfworks/Source/Dwarfworks/Graphics/Camera.h
  Dwarfworks/Source/Dwarfworks/Graphics/RenderCommand.h
  Dwarfworks/Source/Dwarfworks/Graphics/Renderer.cpp
  Dwarfworks/Source/Dwarfworks/Graphics/Renderer.h
  Dwarfworks/Source/Dwarfworks/Graphics/Shader.cpp
  Dwarfworks/Source/Dwarfworks/Graphics/Shader.h
  Dwarfworks/Source/Dwarfworks/Math/Math.h
  Dwarfworks/Source/dwpch.h
Labels: cleanup :new_moon:, enhancement :hammer:, graphics :art:
